// Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/refresh": {
            "get": {
                "description": "restart task manager in order to add new accounts",
                "tags": [
                    "General"
                ],
                "summary": "Restart task manager",
                "operationId": "restart-task-manager",
                "responses": {}
            }
        },
        "/task/": {
            "get": {
                "description": "get all statuses",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Task"
                ],
                "summary": "Get all statuses",
                "operationId": "get-all-status",
                "responses": {}
            }
        },
        "/task/id": {
            "get": {
                "description": "get status by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Task"
                ],
                "summary": "Get status by id",
                "operationId": "get-status-by-id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "account id",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {}
            },
            "put": {
                "description": "get status by ID",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Task"
                ],
                "summary": "Update status by id",
                "operationId": "get-status-by-id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "account id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "new config",
                        "name": "config",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/task.Status"
                        }
                    }
                ],
                "responses": {}
            }
        }
    },
    "definitions": {
        "task.Status": {
            "description": "Model with information about tasks and their parameters",
            "type": "object",
            "properties": {
                "arena_farming": {
                    "type": "boolean"
                },
                "arena_use_energy_cans": {
                    "type": "boolean"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.0.0",
	Host:             "localhost:5504",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Go xaos.mobi bot",
	Description:      "API for xaos.mobi bot",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
