basePath: /
definitions:
  task.Status:
    description: Model with information about tasks and their parameters
    properties:
      arena_farming:
        type: boolean
      arena_use_energy_cans:
        type: boolean
    type: object
host: localhost:5504
info:
  contact: {}
  description: API for xaos.mobi bot
  title: Go xaos.mobi bot
  version: 0.0.0
paths:
  /refresh:
    get:
      description: restart task manager in order to add new accounts
      operationId: restart-task-manager
      responses: {}
      summary: Restart task manager
      tags:
      - General
  /task/:
    get:
      description: get all statuses
      operationId: get-all-status
      produces:
      - application/json
      responses: {}
      summary: Get all statuses
      tags:
      - Task
  /task/id:
    get:
      description: get status by ID
      operationId: get-status-by-id
      parameters:
      - description: account id
        in: query
        name: id
        type: integer
      produces:
      - application/json
      responses: {}
      summary: Get status by id
      tags:
      - Task
    put:
      consumes:
      - application/json
      description: get status by ID
      operationId: get-status-by-id
      parameters:
      - description: account id
        in: query
        name: id
        required: true
        type: integer
      - description: new config
        in: body
        name: config
        required: true
        schema:
          $ref: '#/definitions/task.Status'
      responses: {}
      summary: Update status by id
      tags:
      - Task
swagger: "2.0"
