name: smoke-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
  - cron: "00 12 1 * *"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Install swag
      run: go install github.com/swaggo/swag/cmd/swag@latest

    - name: Generate swagger docs
      run: $GOPATH/bin/swag init --pd

    - name: Install dependencies
      run: go get .

    - name: Build
      run: go build -v ./...
