name: smoke-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
  - cron: "00 12 1 * *"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - run: go install github.com/swaggo/swag/cmd/swag@latest
    - run: $GOBIN/swag init --pd
    - run: go build -v
